version: "3.3"

services:
  db:
    image: mysql:5.7
    #  volumes:
    #    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: devbook
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306


      # create database devbook;
      # show databases;
      # use devbook;
      # create table usuarios( id int auto_increment primary key, nome varchar(50) not null, email varchar(50) not null) ENGINE=INNODB;
      # create user 'golang'@'%' identified by 'golang';
      # grant all privileges on devbook.* to 'golang'@'%';